### ISSUE TITLE
安卓微信出现 keyFrames is not undefined 错误

### ISSUE THREAD

**Issue by xieqingtian** [wenyiweb/canvasKeyFrames#1]
![image](https://user-images.githubusercontent.com/20181476/32203118-2d428790-be1c-11e7-8a49-4279dce34981.png)
经我测试发现是上图中注释部分的问题，注释这部分代码就好了，怀疑是否是安卓微信中drawImage的问题呢？

**Comment by wenyiweb** [comment]
传入图片数组的话是没有问题的，我用安卓手机测试了。我上传了两种模式的示例，你可以看一下~
