### ISSUE TITLE
在RequireJS中引用的时候报Uncaught TypeError: CanvasKeyFrames is not a constructor

### ISSUE THREAD

**Issue by jankerli** [wenyiweb/canvasKeyFrames#2]
没找到原因，我引用其他文件没问题，请教一下

**Comment by jankerli** [comment]
找到问题，要这么调用才不会报错
`new CanvasKeyFrames.CanvasKeyFrames()`
有点不解，为什么~

**Comment by jankerli** [comment]
知道原因了，源代码里是
`return { CanvasKeyFrames: CanvasKeyFrames }`
要改为
`return CanvasKeyFrames`
这样就可以
`new CanvasKeyFrames()`
去使用了~

**Comment by wenyiweb** [comment]
@jankerli 我改一下，发个版本
