### ISSUE TITLE
blob对象怎么用呢？

### ISSUE THREAD

**Issue by cooper1x** [wenyiweb/canvasKeyFrames#4]
我用的preload，图片预加载都会转换成blob地址，请问这种情况怎么操作呢？

**Comment by wenyiweb** [comment]
你可以去研究一下preloadJs的api,和正常使用一样，没什么区别

**Comment by cooper1x** [comment]
我刚刚是把blob的src给new image，然后直接image的src等于blob的src，因为是for循环里面，所以没有写onload事件，不知道这个有没有影响，目前测试还是OK的。

**Comment by wenyiweb** [comment]
你这个图片都是已经预加载过了，直接从缓存拿不会有问题的
